# Generated by Django 2.0.1 on 2018-01-13 17:57

from django.db import migrations


def create_data(apps, schema_editor):
    Topping = apps.get_model('main', 'Topping')
    tomato_topping = Topping.objects.create(name='Tomaten')
    cheese_topping = Topping.objects.create(name='Käse')
    funghi_topping = Topping.objects.create(name='Pilze')
    bell_pepper_topping = Topping.objects.create(name='Paprika')
    hot_pepper_topping = Topping.objects.create(name='Peperoni')
    salami_topping = Topping.objects.create(name='Salami')

    Pizza = apps.get_model('main', 'Pizza')
    margherita_pizza = Pizza.objects.create(name='Pizza Margherita', price_small=3.80, price_big=4.80)
    funghi_pizza = Pizza.objects.create(name='Pizza Funghi', price_small=4.50, price_big=5.50)
    bell_pepper_pizza = Pizza.objects.create(name='Pizza Paprika', price_small=4.50, price_big=5.50)
    hot_pepper_pizza = Pizza.objects.create(name='Pizza Peperoni', price_small=4.50, price_big=5.50)
    salami_pizza = Pizza.objects.create(name='Pizza Salami', price_small=4.50, price_big=5.50)
    special_pizza = Pizza.objects.create(name='Pizza Special', price_small=5.50, price_big=6.50)

    PizzaToppings = apps.get_model('main', 'PizzaTopping')
    # Margherita
    PizzaToppings.objects.create(pizza=margherita_pizza, topping=tomato_topping)
    PizzaToppings.objects.create(pizza=margherita_pizza, topping=cheese_topping)
    # Funghi
    PizzaToppings.objects.create(pizza=funghi_pizza, topping=tomato_topping)
    PizzaToppings.objects.create(pizza=funghi_pizza, topping=cheese_topping)
    PizzaToppings.objects.create(pizza=funghi_pizza, topping=funghi_topping)
    # Bell pepper
    PizzaToppings.objects.create(pizza=bell_pepper_pizza, topping=tomato_topping)
    PizzaToppings.objects.create(pizza=bell_pepper_pizza, topping=cheese_topping)
    PizzaToppings.objects.create(pizza=bell_pepper_pizza, topping=bell_pepper_topping)
    # Hot pepper
    PizzaToppings.objects.create(pizza=hot_pepper_pizza, topping=tomato_topping)
    PizzaToppings.objects.create(pizza=hot_pepper_pizza, topping=cheese_topping)
    PizzaToppings.objects.create(pizza=hot_pepper_pizza, topping=hot_pepper_topping)
    # Salami
    PizzaToppings.objects.create(pizza=salami_pizza, topping=tomato_topping)
    PizzaToppings.objects.create(pizza=salami_pizza, topping=cheese_topping)
    PizzaToppings.objects.create(pizza=salami_pizza, topping=salami_topping)
    # Special
    PizzaToppings.objects.create(pizza=special_pizza, topping=tomato_topping)
    PizzaToppings.objects.create(pizza=special_pizza, topping=cheese_topping)
    PizzaToppings.objects.create(pizza=special_pizza, topping=bell_pepper_topping)
    PizzaToppings.objects.create(pizza=special_pizza, topping=hot_pepper_topping)
    PizzaToppings.objects.create(pizza=special_pizza, topping=salami_topping)


def delete_data(apps, schema_editor):
    PizzaTopping = apps.get_model('main', 'PizzaTopping')
    PizzaTopping.objects.all().delete()
    Topping = apps.get_model('main', 'Topping')
    Topping.objects.all().delete()
    Pizza = apps.get_model('main', 'Pizza')
    Pizza.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data, delete_data)
    ]
